[package]
name = "cli-common"
version = "0.1.0"
edition = "2021"
description = "Shared utilities and common functionality for Double Zero command-line interfaces including transaction execution, account management, and configuration handling"

[dependencies]
anchor-client = { workspace = true }
