[workspace]
members = [
    "programs/*",
    "cli-common"
]
resolver = "2"

[workspace.dependencies]
anchor-client = "0.31.1"
anchor-lang = "0.31.1"
serde="1.0.219"
serde_json = "1.0.141"


[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
