[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock_transfer_program = "9Hij2pLie5j6Nt49s1nozgrLwMqEVKbbF2eABHBF5sWj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mock-transfer-program-tests.ts"
