// pub const SOL_VAULT_SEEDS: &[u8] = b"fee_vault";
// pub const PROTOCOL_TREASURY_SEEDS: &[u8] = b"token_vault";
pub const CONFIGURATION_REGISTRY_SEEDS: &[u8] = b"system_config_v1";
pub const PROGRAM_STATE_SEEDS: &[u8] = b"state_v1";
pub const DENY_LIST_REGISTRY_SEEDS: &[u8] = b"deny_list_v1";
pub const FILLS_REGISTRY_SEEDS: &[u8] = b"fills_registry_v1";
pub const MOCK_2Z_TOKEN_MINT_SEED: &[u8] = b"double_zero_mint";
pub const MOCK_PROTOCOL_TREASURY_SEED: &[u8] = b"protocol_treasury";
pub const MOCK_VAULT_SEED: &[u8] = b"vault";